"""Add currency and link to user and record.

Revision ID: 097dda53b822
Revises: e0baa8fe7637
Create Date: 2025-11-16 21:26:53.968864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097dda53b822'
down_revision = 'e0baa8fe7637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_id', sa.Integer(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'currencies', ['currency_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_currency_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'currencies', ['default_currency_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('default_currency_id')

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('currency_id')

    op.drop_table('currencies')
    # ### end Alembic commands ###
